# Project language
language: php

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

warnings_are_errors: false

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

jobs:
  fast_finish: true
  include:
    - php: 7.4

# Install composer dependencies
install:
  - composer install --prefer-dist --no-interaction
  - ./bin/console doctrine:database:create --env=test
  - ./bin/console doctrine:schema:create --env=test
  - ./bin/console hautelook:fixtures:load --no-interaction --env=test

# Run script
script:
  - ./vendor/bin/simple-phpunit --stop-on-failure
